ks - adding swagger option
ucsb-cs156-s24/proj-courses-s24-4pm-2 pull request #15
Opened 2024-05-18 23:43 UTC by kriteenshrestha

In this PR, I changed the resource file, as the sample PR showed, so that we read from the the environment variable that controlls the swagger link option.

Closes #8

2024-05-21 01:55 UTC, evanja57 approved these changes, later dismissed
LGTM

2024-05-22 01:11 UTC, WhrainySu submitted a review, later dismissed
LGTM

2024-05-22 20:31 UTC, pconrad requested changes
Please see: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-22 20:31 UTC, pconrad commented on src/main/resources/application-development.properties
> +# app.showSwaggerUILink=true
Please remove the commented out line of code.

And team members: please do not put LGTM on a PR that has commented out lines in it.

2024-05-22 23:09 UTC, evanja57 approved these changes
LGTM! For real this time, no commented out code!

2024-05-23 22:00 UTC, pconrad approved these changes
LGTM

2024-05-23 22:00 UTC, merged