Evan course history search output correction
ucsb-cs156-s24/proj-courses-s24-4pm-2 pull request #19
Opened 2024-05-21 07:47 UTC by evanja57

In this pull request, I have updated the CourseOverTimeIndexPage to pass a version of the courseJSON that is sorted by decreasing quarter to the SectionsOverTimeTable, thus enabling it to render in the proper order when called. 

Here is the observed bug for a search on our team's dokku server:
![image](https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/assets/114618731/ae9c564d-434f-4974-8fe3-81283df9f60e)

And here is the fixed version on my dev development:
![image](https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/assets/114618731/e4506d9c-a2c5-4a4d-84af-64a3f129a202)

Originally, it goes oldest to newest, (winter first, then spring), but I have changed it to be the opposite.

Additionally, I had to fix the tests for CourseOverTimeIndexPage in order to pass and kill all mutations, and in doing so I added an extra sectionFixture with entries with different quarters so that I could verify that the sorting by quarter was working properly.

Also, I noticed that also for the building search and the instructor search, the results are displayed with oldest quarter first. For all 3 searches, I believe this is because of the order in which the API returns data, which is why I chose to sort the data when sending it to the SectionsOverTimeTable in the CourseOverTimeIndexPage.

Closes #11

2024-05-22 00:58 UTC, WhrainySu approved these changes
LGTM

2024-05-22 23:31 UTC, AnikaArora requested changes
Overall looks great, but could you please add your dokku dev deployment link for this branch? It'll help us test it ourselves and make sure the functionality works.

2024-05-23 22:07 UTC, evanja57 commented
Just added my dokku dev link to the PR

2024-05-23 22:29 UTC, kmflippo approved these changes
LGTM

2024-05-24 01:04 UTC, AnikaArora approved these changes
LGTM

2024-05-24 01:04 UTC, merged