Kelly - Updating Default Quarter to be S24
ucsb-cs156-s24/proj-courses-s24-4pm-2 pull request #22
Opened 2024-05-22 05:25 UTC by kmflippo

Updating default quarter to be S24

2024-05-22 21:29 UTC, pconrad commented
Remember that bit in the Listening to Developers paper about how sometimes the spec keeps changing?

I promise you: we don't do this on purpose. It just happens naturally, and then you get to learn how real development works.  We are going to change the spec on you for PR22.   The good news is that I think it's a pretty small change, and it should be easy to adjust your PR.

The reason is that I had not communicated my intent clearly to Anika,
who wrote up the issues on my behalf.  So if there's any "blame" to be assigned, assign it to me not her.

So instead of  https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/issues/9
we'd like you to implement https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/issues/23

It's very similar!

2024-05-23 23:10 UTC, kmflippo reviewed
I updated this PR to default the quarter on quarter dropdown to endquarter instead of startquarter

2024-05-26 04:41 UTC, jchanDev requested changes, later dismissed
frontend/src/main/components/Quarters/SingleQuarterDropdown.js has several comments. Please remove them!

2024-05-26 05:17 UTC, jchanDev approved these changes
LGTM

2024-05-26 18:56 UTC, pconrad approved these changes
LGTM!

2024-05-26 18:56 UTC, pconrad commented on frontend/src/main/components/Quarters/SingleQuarterDropdown.js
> +    localStorage.setItem(controlId, "20242");
Instead of hardcoded `20242` this should be the yyyyq member of the **last** element of `quarters` array.

That should be true on line 33 below as well.  See the new issue

https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/issues/23

2024-05-26 18:56 UTC, merged