Kai - Fixed a Bug for the main search
ucsb-cs156-s24/proj-courses-s24-4pm-2 pull request #27
Opened 2024-05-24 01:35 UTC by kai-maeda

Bug: Landing page takes user to the main search. There are many different search pages and the main page may be difficult to find. Currently the user must click on the logo.

Fix: Now clicking on the logo does nothing as the link on the image was removed. Instead another button in the navbar called main search has been placed so that the user can easily find the main page.

<img width="1477" alt="Screenshot 2024-05-23 at 6 32 55 PM" src="https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/assets/102753513/d8974d8f-fdfa-4171-96e7-b8283f5300db">

<img width="1530" alt="Screenshot 2024-05-23 at 6 32 21 PM" src="https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/assets/102753513/5b1b1100-a741-452d-8954-7f61d55bffb9">

Dokku: still building

Closes #13

2024-05-26 20:55 UTC, pconrad submitted a review, later dismissed
Please remove the node_modules directory before we review.

See: 
https://ucsb-cs156.github.io/topics/pull_requests/pull_requests_unwanted_files.html

2024-05-28 05:25 UTC, kmflippo approved these changes, later dismissed
LGTM

2024-05-29 00:38 UTC, jchanDev approved these changes, later dismissed
LGTM!

2024-05-29 21:27 UTC, pconrad requested changes, later dismissed
I have two questions....

(1) I wonder why we are putting ROLE_USER on the basic search? We've never done that before, and I don't think we want to.  Do you see it differently?

(2) Why did you add a package.json at the top level containing prettier?  We typically only work with npm inside the frontend directory.  I think prettier is already there.

2024-05-29 21:27 UTC, pconrad commented on frontend/src/main/components/Nav/AppNavbar.js
> +              )}
Why are we gating this on ROLE_USER?

That requires folks to be logged in.  I don't think we've ever wanted folks to have to be logged in to do simple searchers for courses.  They only need to be logged in if they are building personal schedules or doing admin features.

2024-05-29 21:27 UTC, pconrad commented on package.json
> +}
Why?

2024-05-29 21:27 UTC, pconrad commented on package.json
> +}
Oh, snap... this is not in the frontend directory.  This definitely doesn't belong here.  Please remove it.

2024-05-30 07:14 UTC, kmflippo approved these changes
LGTM

2024-05-31 00:09 UTC, pconrad approved these changes
LGTM

2024-05-31 00:09 UTC, merged